service: udemy-sls-intro

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!./**'
    - src/models/**

provider:
  name: aws
  runtime: python3.9      # 最新ver
  stage: dev              # devで固定
  region: ap-northeast-1  # 東京リージョン
  architecture: arm64     # AWS Graviton2 processor（安くて速いらしい）
  memorySize: 128         # 最小（MB）
  timeout: 6              # デフォルト（seconds）
  versionFunctions: false # バージョン管理しない
  httpApi:
    cors: true            # CORS の許可

functions:
  cy-store-data:
    handler: src/functions/store.handler
    package:
      patterns:
        - src/functions/store.py
    events:
      - httpApi:
          method: POST
          path: /compare-yourself
  cy-delete-data:
    handler: src/functions/delete.handler
    package:
      patterns:
        - src/functions/delete.py
    events:
      - httpApi:
          method: DELETE
          path: /compare-yourself
  cy-get-data:
    handler: src/functions/get.handler
    package:
      patterns:
        - src/functions/get.py
    events:
      - httpApi:
          method: GET
          path: /compare-yourself/{type}
