service: udemy-sls-intro

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9      # 最新ver
  stage: dev              # devで固定
  region: ap-northeast-1  # 東京リージョン
  architecture: arm64     # AWS Graviton2 processor（安くて速いらしい）
  memorySize: 128         # 最小（MB）
  timeout: 6              # デフォルト（seconds）
  versionFunctions: false # バージョン管理しない
  httpApi:
    cors: true            # CORS の許可


functions:
  cy-store-data:
    handler: cy_store_data.handler
    events:
      - httpApi:
          method: POST
          path: /compare-yourself
